### ISSUE TITLE
How to access files inside docker on it's IP address

### ISSUE THREAD

**Issue by richard457** [docker/community#100]
Hello, I have one confusion about docker, normally when I develop website, I can access files under IP:/images/one.png for example but with docker, this no longer works how can I do that?

**Comment by thomasbiddle** [comment]
Hi @richard457 ,

We'd need a lot more information on your setup:
1) Are you running this on a server, or on your own personal machine. If it's your own personal machine and you're trying to access things away from your home - ensure you have port forwarding set up properly.
2) Please provide your `docker run` command - you likely just need to expose the port.
3) Please share exactly how you're attempting to access the file.
