### ISSUE TITLE
compose up error

### ISSUE THREAD

**Issue by fthamura** [docker/community#17]
hi mano

i got this

mervo@sharkbay:~/docker-birthday/community/Docker-Birthday-3/example-voting-app$ docker-compose up
Unsupported config option for services service: 'worker'
mervo@sharkbay:~/docker-birthday/community/Docker-Birthday-3/example-voting-app$

**Comment by vcoisne** [comment]
@fthamura we have moved the tutorial to https://github.com/docker/docker-birthday-3 and fixed a number of issues. Do you still get the same error ?

**Comment by nullck** [comment]
I have the same error here

**Comment by nullck** [comment]
thiagofrancisco➜Dropbox/meetup_docker/voting-app» docker-compose up -d .                                                                                                                         [21:10:50]
Unsupported config option for services service: 'worker'

**Comment by ManoMarks** [comment]
@nullck please stop using this code. Go over to: https://github.com/docker/docker-birthday-3 and clone that repo separately. Then try it from there instead.

**Comment by dbaktiar** [comment]
Hi @ManoMarks, I setup an Ubuntu Wily box from scratch, and still get this error. Likely this is because of the docker-compose version that comes with Ubuntu repository is a bit outdated. However, the default comes from the Ubuntu Wily repo is still pointing to docker-compose 1.3.1.
In my Windows toolbox, it is 1.6.2, and it works nicely.

**Comment by dbaktiar** [comment]
Hi guys, if you still having this problem and running on Ubuntu, follow this instruction:
https://docs.docker.com/compose/install/

**Comment by dbaktiar** [comment]
For Ubuntu users with wrong docker-compose version:
$ sudo apt-get remove docker-compose
$ wget https://github.com/docker/compose/releases/1.6.2/docker-compose-Linux-x86_64
$ mv docker-compose-Linux-x86_64 docker-compose
$ chmod +x docker-compose
$ sudo chown root:root docker-compose
$ sudo mv docker-compose /usr/local/bin/

Need to change x86_64 to something else 'uname -m' for 32 bit Ubuntus.

**Comment by nullck** [comment]
@ManoMarks thanks for your answer, I found my mistake here, I was using the old version of docker toolbox, now after I installed the last version 1.10.3 it's working like expected.

**Comment by alisonalonso** [comment]
Thanks @dbaktiar
