### ISSUE TITLE
Docker command completion plugin for bash

### ISSUE THREAD

**Issue by gautampriya** [docker/community#33]
Is there a command command completion script/plugin for bash shell.

**Comment by arun-gupta** [comment]
Docker bash completion: curl -XGET https://raw.githubusercontent.com/docker/docker/master/contrib/completion/bash/docker > `brew --prefix`/etc/bash_completion.d/docker
Docker Compose bash completion: https://docs.docker.com/compose/completion/

Also filed: https://github.com/docker/docker/issues/21551

**Comment by arun-gupta** [comment]
Docker Machine: https://docs.docker.com/machine/completion/

**Comment by vcoisne** [comment]
Tutorial moved to this repo: https://github.com/docker/labs/tree/master/java
