### ISSUE TITLE
javaee7-simple-sample does not use dockerhost

### ISSUE THREAD

**Issue by 0l33l** [docker/community#36]
curl http://192.168.99.100:8080/javaee7-simple-sample/resources/persons | xml-fmt
should be 
curl http://dockerhost:8080/javaee-simple-sample/resources/persons | xml-fmt

Also, xml-fmt is not installed on macs. Running "brew install XML-Coreutils" fixes this.

**Comment by arun-gupta** [comment]
Second part is duplicate of #37
