### ISSUE TITLE
Stop containers. Possibly command typo?

### ISSUE THREAD

**Issue by heidikumar** [docker/community#38]
In Stop Container section, the command given for stopping all containers is "docker stop $(docker ps -q)". That command didn't work for me. Did you mean -a or -aq?

**Comment by thaJeztah** [comment]
adding `-a` would include containers that are already stopped, so although that won't hurt, it isn't needed. What problem did you run into when using the command? If you got "docker rm requires at least one argument", this can be expected if you didn't have running containers, and `$(docker ps -q)` returned an empty result.

**Comment by arun-gupta** [comment]
@heidikumar do you recall the error that you were getting?

**Comment by vcoisne** [comment]
Tutorial moved to this repo: https://github.com/docker/labs/tree/master/java
