### ISSUE TITLE
Container linking comments should be removed as they no longer apply.

### ISSUE THREAD

**Issue by gautampriya** [docker/community#46]
"Docker Compose applications can use “classic” container linking that is confined to a single host. Alternatively, it can use multi-host networking introduced in Docker 1.9."

From chapter 5, the above text is no longer applicable as networking/linking is taking care of by the docker networking layer in >= 1.10.

A brief explanation of the new linking mechanism would be good. 

A brief section on how to control networking/linking would be nice.

**Comment by vcoisne** [comment]
Tutorial moved to this repo: https://github.com/docker/labs/tree/master/java
