### ISSUE TITLE
Health checks and depends on

### ISSUE THREAD

**Issue by gautampriya** [docker/community#48]
version: '2'
services:
  mycouchbase:
    container_name: "db"
    image: arungupta/couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
  mywildfly:
    image: arungupta/wildfly-couchbase-javaee7
    environment:
      - COUCHBASE_URI=db
    ports:
      - 8080:8080

It would be nice to explain the depends-on feature and health checks. If these features are not yet ready for prime time, it would be nice to add an example of a script that would fill in the gaps for the airline example in chapter 5.

**Comment by arun-gupta** [comment]
There is no built-in support for application-level health check. Filed https://github.com/docker/community/issues/60 for follow up.

Adding support for `depends_on`
