### ISSUE TITLE
minor tweak in ch03.adoc - request to add user instruction

### ISSUE THREAD

**Issue by tgarlick** [docker/community#49]
In chapter 3, under the "Package and Run Java Application using Docker Maven Plugin" section: 

Suggested for minor tweak, after this instruction: 

"Clone the sample code from https://github.com/arun-gupta/docker-java-sample/." 

Would be helpful to prompt user to change to the 'docker-java-sample' directory before creating the docker image (i.e. before running this the “mvn package -Pdocker" command)

**Comment by arun-gupta** [comment]
Duplicate of #39
