### ISSUE TITLE
Scale docker compose is causing Port Conflicts

### ISSUE THREAD

**Issue by srirammageswaran** [docker/community#50]
Hi ,

Scaling docker container in docker compose having a port mapping is causing a port already in use error.

Error below docker-compose.exe scale mywildfly=2
The "mywildfly" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Creating and starting 2 ... error

ERROR: for 2  failed to create endpoint dockerfiles_mywildfly_2 on network dockerfiles_default: Bind for 0.0.0.0:8080 failed: port is already allocated

docker-compose.yml is 

version: '2'
services:
  mycouchbase:
    container_name: "db"
    image: arungupta/couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
  mywildfly:
    image: arungupta/wildfly-couchbase-javaee7
    environment:
      - COUCHBASE_URI=db
    ports:
      - 8080:8080

and the command to scale is : docker-compose.exe scale mywildfly=2.

@kirsid

**Comment by arun-gupta** [comment]
`scale` has not been tested and included in the instructions yet.
