### ISSUE TITLE
add "value proposition" or "problem/solution" intro slide

### ISSUE THREAD

**Issue by tgarlick** [docker/community#51]
At the start of the presentation it was stated (paraphrasing here) that: 

Yes, there's currently a lot of hype around docker, nonetheless, it's believed that docker will be around for a long time because it solves a real problem. 

Can you define the "real problem" succinctly in an intro slide? It may be worthwhile to add an intro slide that states the core issue and, in a line or two, explains how docker addresses / solves the core problem, which ends up being the docker "value prop" to an organization. 

Thanks!

**Comment by arun-gupta** [comment]
Slides are available at https://github.com/docker/community/tree/master/tutorials/java/slides
