### ISSUE TITLE
Docker Error 

### ISSUE THREAD

**Issue by muraliylk** [docker/community#62]
Remove alert
|
Edit
|
Delete
|
Change type
Question
You cannot vote on your own post
0

Hi Team,

Please help me to resolve below issue  

PS C:\Users\Administrator> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engin
e: The system cannot find the file specified.
PS C:\Users\Administrator> docker images
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/json: open //./pipe/docker_e
ngine: The system cannot find the file specified.

**Comment by RupenAnjaria** [comment]
I am facing the same issue, were you able to find solution?
I am using docker for Windows 7 (64):
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v
1.24/version: open //./pipe/docker_engine: The system cannot find the file speci
fied.

**Comment by ManoMarks** [comment]
@RupenAnjaria This repository is for community resources. Can you file an issue here instead? [https://github.com/docker/docker](https://github.com/docker/docker)
