### ISSUE TITLE
New Swarm Mode Presentations

### ISSUE THREAD

**Issue by dstrebel** [docker/community#74]
The Swarm presentation on this repo is outdated. Is there any newer presentation that can be added on Docker Swarm? Something like the "What's new Docker 1.12" from DockerCon 2016?

**Comment by arun-gupta** [comment]
@dstrebel latest Swarm slides are also available at: https://github.com/docker/labs/tree/master/slides

Somebody else can point to the official version.

**Comment by vcoisne** [comment]
thanks @arun-gupta & @dstrebel. We'll update next week. In the meantime you can find the latest swarmkit / swarm mode resource on slideshare http://www.slideshare.net/docker

**Comment by vcoisne** [comment]
We updated the repo. Closing this issue.
