### ISSUE TITLE
map "/var/run/mysqld/mysqld.sock" fails on 16.04 docker

### ISSUE THREAD

**Issue by igenyar** [docker/community#79]
Could someone help take a look at this issue: http://stackoverflow.com/questions/41775664/docker-cannot-map-var-run-mysqld-mysqld-sock ? Basically, I cannot do "-v /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock", which used to work with 12.04 docker. Thanks a lot.

**Comment by ManoMarks** [comment]
please file a bug on https://github.com/docker/docker
