### ISSUE TITLE
How to figure out container image content address remotely?

### ISSUE THREAD

**Issue by urzds** [docker/community#92]
Since a while, container images can be addressed by their content using the `registry/namespace/repository@digest` syntax, where `digest` is usually of the form `sha256:...`. How can I learn this image content address remotely without pulling the image using `docker pull ...` and then running `docker inspect ... | jq -r .[0].RepoDigests[0]`?

The use-case is writing the `FROM` line of a Dockerfile, where I select the base image on e.g. Docker Hub or Quay.io. Neither of the two seems to be able to tell me the digest right away, so I would like to know the `docker` command which prints this or write a script to figure this out.

**Comment by vcoisne** [comment]
@urzds please ask user question either on https://forums.docker.com/ or Docker Community Slack available at dockr.ly/community
