### ISSUE TITLE
Unhelpful "Failed to reset password" on https://id.docker.com/change-password

### ISSUE THREAD

**Issue by krichter722** [docker/community#95]
While attempting to reset my password with Firefox 59.0.2 on Ubuntu 17.10 or Chromium 65.0.3325.181 on https://id.docker.com/change-password/... (link received via mail[1]) I get the feedback `Failed to reset password`:
![screenshot-id docker com-2018-04-03-02-14-47](https://user-images.githubusercontent.com/4369372/38222401-daaadd42-36e4-11e8-9a9d-9becd1c0703a.png)

after pasting the password `bottled barrier potholed faucet` into both the password and the repeat field. If I enter 123 I see a validation message below the field telling me that the password needs to be at least 6 characters long which I don't see after pasting, so the problem might be have another reason. This reason should have been included into the error message.

---
[1] Plaintext mail which contain HTML code look quite unprofessional. I won't open more than one issue before I'm sure that this is the right place, though.

**Comment by thaJeztah** [comment]
Thanks for reporting, but probably the best place to report is through https://github.com/docker/hub-feedback/issues/

**Comment by krichter722** [comment]
Thanks for the pointer. https://github.com/docker/hub-feedback/issues/1445
